### ISSUE TITLE
Train the network with larger images 

### ISSUE THREAD

**Issue by xrafael** [ngctnnnn/Detecting_Abnormalities_CXR#1]
Hi! 

Congratulations for your project, it is helping me a lot.
I have been able to train perfectly your network with other dicom images. 

Just one question, could I train the network with image sizes other 
than 256? I tried to do it but at some point of the first epoch, the network
outputs bboxes with nan values.

Thank you very much for all feedback you can provide me.

Cheers!
-Xavier

**Comment by ngctnnnn** [comment]
I think you have to reconfigure some of the points in the original network setup before training with different image sizes, especially bbox's coordinates

**Comment by xrafael** [comment]
I fixed the issue, I had a bug in my code. So, I can retrain the network with larger images without any   problem.
Thank you!
